version: "3"
networks:
  app-tier:
    driver: bridge

services:
  app:
    image: laravel-www
    container_name: laravel-www
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - mysql
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
    ports:
      - 80:80
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
